# Generated by Django 3.0.4 on 2020-12-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0002_auto_20201221_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='isOwner',
            field=models.BooleanField(default=True),
        ),
    ]
