# Generated by Django 3.0.4 on 2021-03-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_Booked_date',
            field=models.DateField(default=None),
        ),
    ]
