# Generated by Django 3.0.4 on 2021-01-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_No_of_Occupied_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_description',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='isGeared',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_color',
            field=models.CharField(max_length=20),
        ),
    ]
