# Generated by Django 3.0.4 on 2021-03-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0002_auto_20210303_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_Booked_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_Return_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
