# Generated by Django 3.0.4 on 2021-03-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0005_auto_20210303_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_Booked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_Return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
