# Generated by Django 3.0.4 on 2021-03-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0006_auto_20210303_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='Vehicle_Booked_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='Vehicle_Return_date',
        ),
    ]
