# Generated by Django 3.0.4 on 2020-12-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_firstname', models.CharField(max_length=60)),
                ('customer_lastname', models.CharField(max_length=60)),
                ('customer_address', models.CharField(max_length=600)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_dob', models.DateField()),
                ('customer_mobileno', models.CharField(max_length=10)),
                ('customer_age', models.IntegerField(max_length=3)),
                ('customer_license', models.CharField(max_length=600)),
            ],
        ),
    ]
