# Generated by Django 3.0.4 on 2021-01-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manager_firstname', models.CharField(max_length=60)),
                ('Manager_lastname', models.CharField(max_length=60)),
                ('Manager_address', models.CharField(max_length=600)),
                ('Manager_email', models.CharField(max_length=100)),
                ('Manager_password', models.CharField(max_length=32)),
                ('Manager_dob', models.DateField()),
                ('Manager_mobileno', models.CharField(max_length=10)),
                ('Manager_age', models.IntegerField()),
                ('Manager_license', models.CharField(max_length=600)),
                ('Manager_agency', models.CharField(max_length=100)),
                ('Manager_city', models.CharField(max_length=30)),
                ('Manager_state', models.CharField(max_length=30)),
                ('Manager_country', models.CharField(max_length=30)),
                ('Manager_pincode', models.IntegerField()),
                ('isManager', models.BooleanField(default=True)),
            ],
        ),
    ]
