# Generated by Django 3.0.4 on 2021-03-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='Manager_age',
        ),
        migrations.AlterField(
            model_name='manager',
            name='Manager_license',
            field=models.ImageField(upload_to='img/Manager_License/'),
        ),
    ]
