# Generated by Django 3.0.4 on 2021-03-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_auto_20210302_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='Manager_gender',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manager',
            name='Manager_agency',
            field=models.CharField(default='Fast Rentals', max_length=100),
        ),
    ]
