# Generated by Django 3.0.4 on 2021-03-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_auto_20210302_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='isManager',
        ),
        migrations.AddField(
            model_name='manager',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
    ]
