# Generated by Django 3.0.4 on 2021-03-03 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manager', '0003_auto_20210302_1243'),
        ('CustomerHome', '0005_auto_20210129_1237'),
        ('Vehicles', '0001_initial'),
        ('Owner', '0005_auto_20210207_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RentVehicle_Date_of_Rent', models.DateField()),
                ('RentVehicle_Date_of_Return', models.DateField()),
                ('RentVehicle_Total_amount', models.IntegerField()),
                ('isAvailable', models.BooleanField()),
                ('customer_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CustomerHome.Customer')),
                ('manager_authorized_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Manager.Manager')),
                ('owner_authorized_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Owner.Owner')),
                ('vehicle_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Vehicles.Vehicle')),
            ],
        ),
    ]
