# Generated by Django 3.0.4 on 2021-01-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manager', '0001_initial'),
        ('Owner', '0004_owner_owner_password'),
        ('Vehicles', '0002_auto_20210122_1350'),
        ('CustomerHome', '0004_customer_customer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RentVehicle_Date_of_Rent', models.DateField()),
                ('RentVehicle_Date_of_Return', models.DateField()),
                ('RentVehicle_Total_amount', models.IntegerField()),
                ('isAvailable', models.BooleanField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerHome.Customer')),
                ('manager_authorized_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.Manager')),
                ('owner_authorized_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.Owner')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicles.Vehicle')),
            ],
        ),
    ]
