# Generated by Django 3.0.4 on 2021-03-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentVehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentvehicle',
            name='RentVehicle_Date_of_Rent',
        ),
        migrations.RemoveField(
            model_name='rentvehicle',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='rentvehicle',
            name='manager_authorized_id',
        ),
        migrations.RemoveField(
            model_name='rentvehicle',
            name='owner_authorized_id',
        ),
        migrations.RemoveField(
            model_name='rentvehicle',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='rentvehicle',
            name='RentVehicle_Date_of_Booking',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentvehicle',
            name='Vehicle_license_plate',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentvehicle',
            name='customer_email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentvehicle',
            name='isBillPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentvehicle',
            name='request_accepted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rentvehicle',
            name='RentVehicle_Date_of_Return',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentvehicle',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
