# Generated by Django 3.0.4 on 2021-03-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentVehicle', '0002_auto_20210307_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentvehicle',
            name='Advance_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentvehicle',
            name='Total_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
