# Generated by Django 3.0.4 on 2021-01-22 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerHome', '0004_customer_customer_password'),
        ('Manager', '0001_initial'),
        ('Vehicles', '0002_auto_20210122_1350'),
        ('Owner', '0004_owner_owner_password'),
        ('RentVehicle', '0002_auto_20210122_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentvehicle',
            name='customer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CustomerHome.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentvehicle',
            name='manager_authorized_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Manager.Manager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentvehicle',
            name='owner_authorized_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Owner.Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentvehicle',
            name='vehicle_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Vehicles.Vehicle'),
            preserve_default=False,
        ),
    ]
